runtime: php  # language of the app
env: flex     # let app engine know we use flexible environment
runtime_config:
 document_root: public   #folder where index.php is
# Ensure we skip ".env", which is only for local development

env_variables:
 # Put production environment variables here.
 APP_ENV: local   # or production
 APP_DEBUG : true # or false 
 APP_KEY: base64:z9Ag4WipVQTRLF/yBBG510ePw8XYLW+DBJW3NVZNCBc=
#go to generate app key paragraf in this tutorial
 CACHE_DRIVER: database
# instead of putting the cache in the database I recommend using redis
 SESSION_DRIVER: database #or file since both work
 APP_LOG: daily
 APP_TIMEZONE: UTC #your timezone of choice
# follow the part of the tutorial on setting up your SQL database
 DB_CONNECTION: mysql
 DB_HOST: 34.95.168.120
 DB_DATABASE: SIRAC2
 DB_USERNAME: admin
 DB_PASSWORD: admin
 MAIL_DRIVER:
 MAIL_HOST: 
 MAIL_PORT: 
 MAIL_USERNAME: 
 MAIL_PASSWORD: 
 LOG_DELETE:  true # this is a parameter added by us in the project .env file. You can add here any setting you would add to your .env file
 GOOGLE_VISION_PROJECT_ID : project_id
#we need this for the flex environment
beta_settings:
   # for Cloud SQL, set this value to the Cloud SQL connection name,
   # e.g. "project:region:cloudsql-instance"
   cloud_sql_instances: project:cloudsql-instance